spring:
  application:
    name: payment-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/paymentservice}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: ${SERVER_PORT:8085}

shop:
  kafka:
    bootstrap-servers: ${SHOP_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  payment:
    provider: ${PAYMENT_PROVIDER:mock}
    webhook:
      secret: ${PAYMENT_WEBHOOK_SECRET:}
    stripe:
      secret-key: ${STRIPE_SECRET_KEY:}

  security:
    issuer-uri: ${SHOP_SECURITY_ISSUER_URI:http://localhost:9090/realms/ecommerce}
    csrf-disabled: true
    stateless-session: true
