#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

SONAR_HOST="${SONAR_HOST:-http://localhost:9000}"
SONAR_ADMIN_USER="${SONAR_ADMIN_USER:-admin}"
SONAR_ADMIN_PASS="${SONAR_ADMIN_PASS:-admin}"
SONAR_NEW_ADMIN_PASS="${SONAR_NEW_ADMIN_PASS:-Shop#Sonar2026!Strict}"
PROJECT_KEY="${SONAR_PROJECT_KEY:-petproject}"
PROJECT_NAME="${SONAR_PROJECT_NAME:-petproject}"
ENV_FILE="$REPO_ROOT/.env.sonar"

echo "==> 1. Waiting for SonarQube to become UP at $SONAR_HOST..."
MAX_RETRIES=60
RETRY_COUNT=0
until curl -fsSL "$SONAR_HOST/api/system/status" 2>/dev/null | grep -q '"status":"UP"'; do
    RETRY_COUNT=$((RETRY_COUNT + 1))
    if [ "$RETRY_COUNT" -ge "$MAX_RETRIES" ]; then
        echo "ERROR: Timed out waiting for SonarQube to start."
        exit 1
    fi
    echo "SonarQube not ready yet. Retrying ($RETRY_COUNT/$MAX_RETRIES) in 5s..."
    sleep 5
done
echo "SonarQube is UP!"

# Determine working credentials
AUTH_HEADER=""
if [ -f "$ENV_FILE" ]; then
    # shellcheck disable=SC1090
    source "$ENV_FILE"
fi

# Check if existing token works
if [ -n "${SONAR_TOKEN:-}" ]; then
    VALID_RESP=$(curl -s -u "${SONAR_TOKEN}:" "$SONAR_HOST/api/authentication/validate" 2>/dev/null || true)
    if echo "$VALID_RESP" | grep -q '"valid":true'; then
        echo "Existing SONAR_TOKEN from .env.sonar is valid."
        AUTH_HEADER="${SONAR_TOKEN}:"
    fi
fi

if [ -z "$AUTH_HEADER" ]; then
    # Try new password first
    if curl -s -f -u "$SONAR_ADMIN_USER:$SONAR_NEW_ADMIN_PASS" "$SONAR_HOST/api/users/current" >/dev/null 2>&1; then
        echo "Authenticated with configured admin password."
        AUTH_HEADER="$SONAR_ADMIN_USER:$SONAR_NEW_ADMIN_PASS"
    elif curl -s -f -u "$SONAR_ADMIN_USER:$SONAR_ADMIN_PASS" "$SONAR_HOST/api/users/current" >/dev/null 2>&1; then
        echo "Default admin credentials active. Changing password..."
        curl -fsS -u "$SONAR_ADMIN_USER:$SONAR_ADMIN_PASS" -X POST "$SONAR_HOST/api/users/change_password" \
            -d "login=$SONAR_ADMIN_USER&password=$SONAR_NEW_ADMIN_PASS&previousPassword=$SONAR_ADMIN_PASS"
        echo "Admin password changed successfully."
        AUTH_HEADER="$SONAR_ADMIN_USER:$SONAR_NEW_ADMIN_PASS"
    else
        echo "ERROR: Unable to authenticate with admin credentials."
        exit 1
    fi
fi

# 2. Create project if it doesn't exist
echo "==> 2. Ensuring project '$PROJECT_KEY' exists..."
SEARCH_PROJECT=$(curl -fsS -u "$AUTH_HEADER" "$SONAR_HOST/api/projects/search?projects=$PROJECT_KEY" 2>/dev/null || true)
if ! echo "$SEARCH_PROJECT" | grep -q "\"key\":\"$PROJECT_KEY\""; then
    echo "Creating project '$PROJECT_KEY'..."
    curl -fsS -u "$AUTH_HEADER" -X POST "$SONAR_HOST/api/projects/create" \
        -d "project=$PROJECT_KEY&name=$PROJECT_NAME"
    echo "Project '$PROJECT_KEY' created."
else
    echo "Project '$PROJECT_KEY' already exists."
fi

# 3. Generate token if needed
if [ -z "${SONAR_TOKEN:-}" ] || [ "$AUTH_HEADER" != "${SONAR_TOKEN}:" ]; then
    echo "==> 3. Generating CI token for '$PROJECT_KEY'..."
    TOKEN_NAME="ci-$PROJECT_KEY-$(date +%s)"
    TOKEN_JSON=$(curl -fsS -u "$AUTH_HEADER" -X POST "$SONAR_HOST/api/user_tokens/generate" \
        -d "name=$TOKEN_NAME")
    SONAR_TOKEN=$(echo "$TOKEN_JSON" | grep -o '"token":"[^"]*"' | cut -d'"' -f4)
fi

# 4. Save to .env.sonar
cat > "$ENV_FILE" <<EOF
# generated by scripts/setup-sonar-project.sh — do not commit (gitignored)
SONAR_HOST_URL=$SONAR_HOST
SONAR_TOKEN=$SONAR_TOKEN
SONAR_PROJECT_KEY=$PROJECT_KEY
EOF
chmod 600 "$ENV_FILE"
echo "Saved credentials to $ENV_FILE"

# 5. Quality gate setup
echo "==> 4. Configuring 'petproject-strict' quality gate..."
GATE_LIST=$(curl -fsS -u "$SONAR_TOKEN:" "$SONAR_HOST/api/qualitygates/list" 2>/dev/null || true)
if ! echo "$GATE_LIST" | grep -q '"name":"petproject-strict"'; then
    echo "Creating 'petproject-strict' quality gate..."
    curl -fsS -u "$SONAR_TOKEN:" -X POST "$SONAR_HOST/api/qualitygates/create" \
        -d "name=petproject-strict"

    # Add strict conditions (Sonar Way + Strict)
    curl -fsS -u "$SONAR_TOKEN:" -X POST "$SONAR_HOST/api/qualitygates/create_condition" \
        -d "gateName=petproject-strict&metric=new_coverage&op=LT&error=80" || true
    curl -fsS -u "$SONAR_TOKEN:" -X POST "$SONAR_HOST/api/qualitygates/create_condition" \
        -d "gateName=petproject-strict&metric=new_duplicated_lines_density&op=GT&error=3" || true
    curl -fsS -u "$SONAR_TOKEN:" -X POST "$SONAR_HOST/api/qualitygates/create_condition" \
        -d "gateName=petproject-strict&metric=new_maintainability_rating&op=GT&error=1" || true
    curl -fsS -u "$SONAR_TOKEN:" -X POST "$SONAR_HOST/api/qualitygates/create_condition" \
        -d "gateName=petproject-strict&metric=new_reliability_rating&op=GT&error=1" || true
    curl -fsS -u "$SONAR_TOKEN:" -X POST "$SONAR_HOST/api/qualitygates/create_condition" \
        -d "gateName=petproject-strict&metric=new_security_rating&op=GT&error=1" || true
    echo "'petproject-strict' quality gate created and conditions configured."
else
    echo "Quality gate 'petproject-strict' already exists."
fi

# Assign to project
echo "==> 5. Assigning 'petproject-strict' to '$PROJECT_KEY'..."
curl -fsS -u "$SONAR_TOKEN:" -X POST "$SONAR_HOST/api/qualitygates/select" \
    -d "gateName=petproject-strict&projectKey=$PROJECT_KEY" || true

echo "SonarQube project setup complete! Ready to scan."
